# Generated by Django 3.1.2 on 2020-10-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmp_app', '0002_auto_20201002_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file_id',
            field=models.CharField(default='empty', max_length=256),
        ),
    ]
